### ISSUE TITLE
Can't deploy units from factories if there are obstacles [$5]

### ISSUE THREAD

**Issue by Fincer** [OpenRA/ra2#137] opened 2016-02-13 21:55 UTC
This issue is clearly visible here in the following Youtube video:

http://www.youtube.com/watch?v=QrL8m48TePY&t=4m43s

In the video, I was producing a few ships. However, I noticed that the ships couldn't be deployed so I tried to set a waypoint and repeat the building process again. Still no luck. My final conclusion was that I needed to sell the existing Naval Yard and construct it again offshore so that naval units could expectedly be deployed.

When a Naval Yard locates near a shoreline, expected behaviour is that units would be deployed from the furthest corner of the building (or something alike) so that this issue wouldn't exist

**Comment by Fincer** [comment] 2016-02-13 22:14
Same kind of problem with Cloning Vats:

![cantproduce-openra2](https://cloud.githubusercontent.com/assets/3705231/13030342/c5fad320-d2af-11e5-885c-aa1b242f549f.gif)

Cloned infantry would never be deployed. I sold my ConYard and couldn't see cloned infantry there.

**Comment by abcdefg30** [comment] 2016-02-13 23:06
That is expected behaviour. If you block all exits, the units can't and won't leave the building.
But I guess e.g. the naval yard could use quite a few more exits...

**Comment by Fincer** [comment] 2016-02-14 00:59
Well, not exactly. This is how it works in the original RA2:

![cantproduce-ra2-cropped](https://cloud.githubusercontent.com/assets/3705231/13031055/d9c60fa2-d2c6-11e5-9fe1-ac1cee48c85c.gif)

You can clearly see cloned units coming out from the Cloning Vats as well, using just another/opposite direction. This is not the case in OpenRA/ra2.

**Comment by Icenowy** [comment] 2016-04-11 13:05
As I know, at least War Factories will be not able to produce anything if they're all blocked in original RA2.(I've heard this as some tactics, that if you use vehicles to block all the enemies' war factories, the vehicles in the task queue will just lost, and the money is cost) (But in OpenRA the money won't be cost, only the vehicle task queue will be on hold)

**Comment by MustaphaTR** [comment] 2016-04-11 13:42
> the vehicles in the task queue will just lost, and the money is cost

Not sure about WFAC but infantry in RA2 that coudn't build gives The money back. There is even a bug that u can wall your barracks and u'll still get a free unit from Cloning Vats, but this is fixed in Ares.dll.

**Comment by Icenowy** [comment] 2016-04-12 05:52
@MustaphaTR You're right. (This cloning bug seems to be also fixed in NPatch AE)

And my experiment shows that on original RA2 infantry will try to escape the structure from any hole of the wall around the structure.

**Comment by Phrohdoh** [comment] 2016-06-28 14:34
@abcdefg30 How would you feel about all perimeter cells being exits?

If after that is setup someone manages to block every cell of the barracks/vat then that is user error and nothing more can be done.

**Comment by abcdefg30** [comment] 2016-06-28 17:07
Sounds good.

**Comment by Phrohdoh** [comment] 2016-06-29 20:45
Is everyone alright with me collecting the bounty via #250?

**Comment by GraionDilach** [comment] 2016-06-29 21:13
I'm fine with that, yeah.

**Comment by Phrohdoh** [comment] 2016-06-29 23:42
Turns out I can only do so once this is closed.
@Fincer do you consider my merged PR a solution?

**Comment by Fincer** [comment] 2016-06-30 05:19
Yup, looks good to me.

**Closed** 2016-06-30 12:14 UTC
Labels: Bounty, Polish
