### ISSUE TITLE
Crash when creating power plant

### ISSUE THREAD

**Issue by davidacampos** [OpenRA/ra2#222] opened 2016-05-26 20:01 UTC
Not sure if this is an ra2 or OpenRA issue. Whenever I start a game, the first thing after deploying the base is building a power plant. When it finishes building the plant it throws the following exception:

```
Red Alert 2 Mod at Version {DEV_VERSION}
on map dae1d2a018fde88fae2cbf502823ff0918a132d4 (Breakaway by Westwood Studios).
Operating System: Windows (Microsoft Windows NT 6.2.9200.0)
Runtime Version: .NET CLR 4.0.30319.42000
Exception of type "System.InvalidOperationException": Actor does not have trait of type "OpenRA.Mods.Common.Traits.PowerManager"
   at OpenRA.TraitDictionary.TraitContainer"1.Get(UInt32 actor) in c:\Users\<user>\Downloads\OpenRA-bleed\OpenRA.Game\TraitDictionary.cs:line 151
   at OpenRA.TraitDictionary.Get[T](Actor actor) in c:\Users\<user>\Downloads\OpenRA-bleed\OpenRA.Game\TraitDictionary.cs:line 89
   at OpenRA.Actor.Trait[T]() in c:\Users\<user>\Downloads\OpenRA-bleed\OpenRA.Game\Actor.cs:line 247
   at OpenRA.Mods.RA.Traits.InfiltrateForPowerOutage..ctor(Actor self, InfiltrateForPowerOutageInfo info)
   at OpenRA.Mods.RA.Traits.InfiltrateForPowerOutageInfo.Create(ActorInitializer init)
   at OpenRA.Actor..ctor(World world, String name, TypeDictionary initDict) in c:\Users\<user>\Downloads\OpenRA-bleed\OpenRA.Game\Actor.cs:line 102
   at OpenRA.World.CreateActor(Boolean addToWorld, String name, TypeDictionary initDict) in c:\Users\<user>\Downloads\OpenRA-bleed\OpenRA.Game\World.cs:line 247
   at OpenRA.World.CreateActor(String name, TypeDictionary initDict) in c:\Users\<user>\Downloads\OpenRA-bleed\OpenRA.Game\World.cs:line 242
   at OpenRA.Mods.Common.Traits.PlaceBuilding.<>c__DisplayClass6.<ResolveOrder>b__2(World w)
   at OpenRA.World.Tick() in c:\Users\<user>\Downloads\OpenRA-bleed\OpenRA.Game\World.cs:line 326
   at OpenRA.Game.InnerLogicTick(OrderManager orderManager) in c:\Users\<user>\Downloads\OpenRA-bleed\OpenRA.Game\Game.cs:line 522
   at OpenRA.Game.LogicTick() in c:\Users\<user>\Downloads\OpenRA-bleed\OpenRA.Game\Game.cs:line 547
   at OpenRA.Game.Loop() in c:\Users\<user>\Downloads\OpenRA-bleed\OpenRA.Game\Game.cs:line 674
   at OpenRA.Game.Run() in c:\Users\<user>\Downloads\OpenRA-bleed\OpenRA.Game\Game.cs:line 714
   at OpenRA.Program.Run(String[] args) in c:\Users\<user>\Downloads\OpenRA-bleed\OpenRA.Game\Support\Program.cs:line 118
   at OpenRA.Program.Main(String[] args) in c:\Users\<user>\Downloads\OpenRA-bleed\OpenRA.Game\Support\Program.cs:line 40
```

Using Windows 10 and latest code (from around 10 minutes ago... for both OpenRA and ra2)

Thanks!

**Comment by abcdefg30** [comment] 2016-05-26 20:25
Hm, looks similiar to https://github.com/OpenRA/ra2/issues/221#issuecomment-221975995.
This can't really be our error as the player actor has indeed the `PowerManager` trait: https://github.com/OpenRA/ra2/blob/master/rules/player.yaml#L44

**Comment by Sbubbolio** [comment] 2016-05-26 21:06
I just tested the skirmish game and I've got the same error.
I deployed the MCV, I started the building of a power plant and I got it.

```
Red Alert 2 Mod at Version {DEV_VERSION}
on map dae1d2a018fde88fae2cbf502823ff0918a132d4 (Breakaway by Westwood Studios).
Operating System: Windows (Microsoft Windows NT 6.1.7601 Service Pack 1)
Runtime Version: .NET CLR 4.0.30319.34209
Exception of type `System.InvalidOperationException`: Actor does not have trait of type `OpenRA.Mods.Common.Traits.PowerManager`
   in OpenRA.TraitDictionary.TraitContainer`1.Get(UInt32 actor) in c:\Giochi\OpenRA-bleed\OpenRA.Game\TraitDictionary.cs:riga 151
   in OpenRA.TraitDictionary.Get[T](Actor actor) in c:\Giochi\OpenRA-bleed\OpenRA.Game\TraitDictionary.cs:riga 89
   in OpenRA.Actor.Trait[T]() in c:\Giochi\OpenRA-bleed\OpenRA.Game\Actor.cs:riga 247
   in OpenRA.Mods.RA.Traits.InfiltrateForPowerOutage..ctor(Actor self, InfiltrateForPowerOutageInfo info)
   in OpenRA.Mods.RA.Traits.InfiltrateForPowerOutageInfo.Create(ActorInitializer init)
   in OpenRA.Actor..ctor(World world, String name, TypeDictionary initDict) in c:\Giochi\OpenRA-bleed\OpenRA.Game\Actor.cs:riga 102
   in OpenRA.World.CreateActor(Boolean addToWorld, String name, TypeDictionary initDict) in c:\Giochi\OpenRA-bleed\OpenRA.Game\World.cs:riga 247
   in OpenRA.World.CreateActor(String name, TypeDictionary initDict) in c:\Giochi\OpenRA-bleed\OpenRA.Game\World.cs:riga 242
   in OpenRA.Mods.Common.Traits.PlaceBuilding.<>c__DisplayClass6.<ResolveOrder>b__2(World w)
   in OpenRA.World.Tick() in c:\Giochi\OpenRA-bleed\OpenRA.Game\World.cs:riga 326
   in OpenRA.Game.InnerLogicTick(OrderManager orderManager) in c:\Giochi\OpenRA-bleed\OpenRA.Game\Game.cs:riga 522
   in OpenRA.Game.LogicTick() in c:\Giochi\OpenRA-bleed\OpenRA.Game\Game.cs:riga 547
   in OpenRA.Game.Loop() in c:\Giochi\OpenRA-bleed\OpenRA.Game\Game.cs:riga 674
   in OpenRA.Game.Run() in c:\Giochi\OpenRA-bleed\OpenRA.Game\Game.cs:riga 714
   in OpenRA.Program.Run(String[] args) in c:\Giochi\OpenRA-bleed\OpenRA.Game\Support\Program.cs:riga 118
   in OpenRA.Program.Main(String[] args) in c:\Giochi\OpenRA-bleed\OpenRA.Game\Support\Program.cs:riga 40
```

**Comment by Walkman100** [comment] 2016-05-26 21:48
This is the exact error I get from my [build script](https://github.com/Walkman100/OpenRA-Install-Guide/blob/88f0d565514d7b38b6478a22153e8184101e9af9/Install-RA2/InstallRA2.bat), and I get it 100% of the time. It only occurs for me when PLACING the plant, if I play a skirmish with just me and no bots then I can test the exact moment it crashes.

**Comment by GraionDilach** [comment] 2016-05-26 22:56
I couldn't confirm this, but a reason did popped up in my mind. Could you guys tell me if you were trying this out before #215 got merged? I'd really like to blame a .NET version mismatch mishap and not something superdeep serious.

**Comment by Walkman100** [comment] 2016-05-26 23:16
no, the crash is from before - my build script checks out a commit from 7 days ago (I tested the latest on OpenRA and latest here and it crashes when loading the mod)

**Comment by GraionDilach** [comment] 2016-05-26 23:18
Yes, currently the RA2 mod is working up to revision https://github.com/OpenRA/OpenRA/tree/b6afc765b4be0b0289471c25c450d79eb948d3d3  with me just filing a PR to get the mod compatible with that one commit merged since this one.

The .NET version mishap sounds more legit by now though.

**Comment by Walkman100** [comment] 2016-05-26 23:39
alright, thanks for that, I've [updated my script](https://github.com/Walkman100/OpenRA-Install-Guide/commit/8a8e8208fc89908005688ec717b9b75f8c817a53) to use latest on this repo and https://github.com/OpenRA/OpenRA/commit/b6afc765b4be0b0289471c25c450d79eb948d3d3
I still get the EXACT same error as before though.

**Comment by GraionDilach** [comment] 2016-05-27 07:07
You can use the latest on both again (#223 got the two synced together again) - could you please nuke the folder entirely and rebuild everything?

**Comment by Walkman100** [comment] 2016-05-27 14:45
I've been doing that every time I build it.
Updated the script, built the new version, it loaded fine but still crashes when placing a power building.

**Comment by GraionDilach** [comment] 2016-05-27 15:58
Huh. I'll try to look at this, but I just changed my PC and now I'm affected with an OpenGL driver bug (which crashes the gen2 mods) and the GPU I ordered only arrives in Monday at best, so I cannot promise that I can fix this during the weekend.

**Comment by GraionDilach** [comment] 2016-06-08 11:14
I still haven't got my GPU, but I managed to run RA2 somewhat on my current one and I cannot confirm this still. I'm aware that there are a lot of reports regarding this bug but I really have no idea why.

**Comment by Walkman100** [comment] 2016-06-12 17:49
More info on this issue: I used my [Linux build script](https://github.com/Walkman100/OpenRA-Install-Guide/blob/master/Install-RA2/install-ra2.sh) to build this, which checks out the exact same commits as the Windows build script, and the game runs 100% fine.

I'm pretty sure it was still crashing with those commits, so when I'm next in windows I'll test that.
I'm also going to test whether the copy compiled in Linux works in windows (will have to do some symlink magic)

**Comment by Walkman100** [comment] 2016-06-12 17:51
Trying to run the Windows-compiled copy on Linux results in:
```
Renderer initialization failed. Fallback in place. Check graphics.log for details.
Exception of type `System.InvalidOperationException`: No suitable renderers were found. Check graphics.log for details.
  at OpenRA.Game.Initialize (OpenRA.Arguments args) <0x41765d70 + 0x00737> in <filename unknown>:0
  at OpenRA.Program.Run (System.String[] args) <0x41729aa0 + 0x0004f> in <filename unknown>:0
  at OpenRA.Program.Main (System.String[] args) <0x41728d60 + 0x0010f> in <filename unknown>:0
```
[graphics.log.txt](https://github.com/OpenRA/ra2/files/310885/graphics.log.txt)

**Comment by abcdefg30** [comment] 2016-06-12 21:29
> System.DllNotFoundException: SDL2.dll

Seems like you're missing a dependency?

**Comment by Walkman100** [comment] 2016-06-13 00:05
`SDL2.dll` exists in the OpenRA directory I'm running it from (I'm running `bash launch-game.sh` from the OpenRA dir)
I assume it's a dependency incompatibility of some sort between a copy compiled on Windows and Linux

**Comment by Phrohdoh** [comment] 2016-06-29 14:27
@davidacampos Could you please:
1) checkout and build the latest OpenRA commit (OpenRA/OpenRA@641cb96dac003cd9bdeba3e4414b532687e55135 at the time of writing)
2) checkout the latest RA2 commit (6d1c36dbc873bc355dc6ee23c610718f45aea259)
3) save the below script to your RA2 mod root and run it
4) build RA2 and try to reproduce this issue

```bash
#!/usr/bin/env bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

while [ -z "$OPENRA_ROOT" ]; do
	read -p "Enter the path to your OpenRA root: " OPENRA_ROOT
done

OPENRA_ROOT="${OPENRA_ROOT/\~/$HOME}"

DEST="$DIR/OpenRA.Mods.RA2/dependencies"

deps=("Eluant.dll" "OpenRA.Game.exe" "OpenRA.Mods.Common.dll" "OpenRA.Mods.RA.dll" "OpenRA.Mods.TS.dll")
for dep in "${deps[@]}"; do
	SRC="${OPENRA_ROOT}/$dep"
	cp "$SRC" "$DEST" 2>/dev/null || :

	if [ ! -f "$DEST/$dep" ]; then
		find "$OPENRA_ROOT" -iname "$dep" -exec cp {} "$DEST" \;
	fi

	if [ ! -f "$DEST/$dep" ]; then
		echo "Failed to copy '$SRC' to '$DEST', please do so manually."
	fi
done
```

Example:
```
tmba:ra2 thill $ pwd
/Users/thill/Library/Application Support/OpenRA/mods/ra2
tmba:ra2 thill $ ./fetch-deps.bash
Enter the path to your OpenRA root: ~/projects/openra
```

**Comment by Valkirie** [comment] 2016-07-03 10:25
Easy fix here. Don't know if it's something missing within the step to step guide or installation scripts that can be found online.

DLLs inside .\OpenRA\OpenRA.Mods.RA2\bin\Debug\ has to be moved to their respective folders (.mods\ra\) (.\mods\ts\) (.\mods\ra2) (.\mods\common).

**Comment by Mailaender** [comment] 2016-07-04 05:56
Probably a regression from https://github.com/OpenRA/ra2/pull/230.

**Comment by abcdefg30** [comment] 2016-07-14 16:53
I can't reproduce this on the latest versions, so closing except you can provide a reproduction case.

**Closed by abcdefg30** 2016-07-14 16:53 UTC
Labels: Crash
