### ISSUE TITLE
Idea: Structure Garrison

### ISSUE THREAD

**Issue by cookgreen** [OpenRA/ra2#356] opened 2017-02-02 13:54 UTC
Troops in ra2 can't enter the building and make it a garrison

I think we can add support for it

**Comment by MustaphaTR** [comment] 2017-02-02 14:13
Duplicate of: https://github.com/OpenRA/OpenRA/issues/11214

**Comment by ibrokemypie** [comment] 2017-02-05 05:09
close this one?

**Comment by abcdefg30** [comment] 2017-02-05 21:17
I hope this will be done upstream then.

**Closed** 2017-02-05 21:17 UTC
Labels: Enhancement
