### ISSUE TITLE
Only one slot can be used in Airforce Command Headquarter

### ISSUE THREAD

**Issue by hathlife** [OpenRA/ra2#605] opened 2020-01-26 18:18 UTC
When produce mutli aircrafts, only first aircraft produced can land in left slot, the others just hover above the building. 
[See here](https://h0nm4m31k0.tk/index.php/2020/01/27/openra-ra2-issue-605/)

**Comment by abcdefg30** [comment] 2020-01-26 18:23
Thanks for the report. Duplicate of #87 however.

**Closed by abcdefg30** 2020-01-26 18:23 UTC
