### ISSUE TITLE
Chrono Leigionare currently uses chrono-tank behaviour

### ISSUE THREAD

**Issue by thennothinghappened** [OpenRA/ra2#755] opened 2020-11-30 03:29 UTC
Currently the behaviour from the chrono-tank is used, meaning that they have limited range, and also do not have the ability to 'disable' buildings while shooting at them.

**Comment by Mailaender** [comment] 2021-03-22 14:21
Duplicate of https://github.com/OpenRA/ra2/issues/174.

**Closed by Mailaender** 2021-03-22 14:21 UTC
