### ISSUE TITLE
Can't locate type 'UpgradeManagerInfo'

### ISSUE THREAD

**Issue by cookgreen** [OpenRA/ra2#346] opened 2016-12-31 14:24 UTC
`Exception of type `System.InvalidOperationException`: Cannot locate type: UpgradeManagerInfo`

**Comment by MustaphaTR** [comment] 2016-12-31 15:46
Upgrades are removed and replaced by conditions on upstream. RA2 mod has not upgraded for it yet.

**Comment by cookgreen** [comment] 2016-12-31 15:51
but how to fix it? where to find the 'upgrademanagerinfo'? i try to search it in RA2 source code but failed

**Comment by MustaphaTR** [comment] 2016-12-31 15:53
It is bot anything to do with C# code. It is about .yaml. UpgradeManagerInfo is replaced as i said.

**Comment by cookgreen** [comment] 2016-12-31 15:54
And i debug the OpenRA source code, and still can't find.
I have found the problem is caused in Ruleset Function(OpenRA), the property 'DefaultRules' of ModData instance - moddata cased this error.

**Comment by MustaphaTR** [comment] 2016-12-31 15:54
You can't find it because it no longer exists.

**Comment by cookgreen** [comment] 2016-12-31 15:55
did you mean mod.yaml? i searched, but no results

**Comment by MustaphaTR** [comment] 2016-12-31 15:56
No, .yaml files under rules folder and UpgradeManagerInfo is not really what you need to search, give me a sec to find the PR about it.

**Comment by cookgreen** [comment] 2016-12-31 15:57
But which gives the openra this wrong parameter? something like yaml?

**Comment by MustaphaTR** [comment] 2016-12-31 15:58
Tags that are removed/replaced.

**Comment by cookgreen** [comment] 2016-12-31 16:00
okay, so how did we fix it?

**Comment by MustaphaTR** [comment] 2016-12-31 16:00
https://github.com/OpenRA/OpenRA/pull/12497/files

The tag `UpgradeManager:` is renamed to `ConditionManager:` that is the reason of error.

**Comment by cookgreen** [comment] 2017-01-01 02:19
I have fixed this error and create a pull request

**Comment by GraionDilach** [comment] 2017-01-17 18:23
Reverse duplicate of #354.

**Closed by GraionDilach** 2017-01-17 18:23 UTC
Labels: Crash
