### ISSUE TITLE
Tesla Reactor rendering issue

### ISSUE THREAD

**Issue by Fincer** [OpenRA/ra2#147] opened 2016-02-22 20:22 UTC
I noticed this while I was playing as soviets today.

![teslagen_bug_openra](https://cloud.githubusercontent.com/assets/3705231/13231351/28f855e8-d9b2-11e5-919b-d2c9c7481de0.png)

As far as I can tell, only that specific corner of the building seems to be affected. At least I can't see any visually strange glitches occuring on the other corners of a Tesla Reactor.

**Comment by pchote** [comment] 2016-03-19 12:36
Duplicate of #127, OpenRA/OpenRA#7520.

**Comment by Mailaender** [comment] 2020-03-16 20:50
This doesn't happen anymore.

**Closed by Mailaender** 2020-03-16 20:50 UTC
Labels: Polish
