### ISSUE TITLE
Exception of type `System.AggregateException`: One or more errors occurred

### ISSUE THREAD

**Issue by veleiro** [OpenRA/ra2#353] opened 2017-01-16 00:55 UTC
hello.  I just tried to compile and run using the instructions at https://github.com/OpenRA/ra2/wiki/Step-by-Step

RA2 mod appears in the mod list in game, but when I try to load it, i get the following error:

`Exception of type `System.AggregateException`: One or more errors occurred.
Inner
  Exception of type `System.InvalidOperationException`: Cannot locate type: UpgradeManagerInfo
    at OpenRA.ObjectCreator.<MissingTypeAction>m__6 (System.String s) [0x00015] in <a10404fca1ef4990a0ba356e4aea33c3>:0 
  at OpenRA.ObjectCreator.CreateObject[T] (System.String className, System.Collections.Generic.Dictionary`2[TKey,TValue] args) [0x0001b] in <a10404fca1ef4990a0ba356e4aea33c3>:0 
  at OpenRA.ObjectCreator.CreateObject[T] (System.String className) [0x00008] in <a10404fca1ef4990a0ba356e4aea33c3>:0 
  at OpenRA.ActorInfo.LoadTraitInfo (OpenRA.ObjectCreator creator, System.String traitName, OpenRA.MiniYaml my) [0x00040] in <a10404fca1ef4990a0ba356e4aea33c3>:0 
  at OpenRA.ActorInfo..ctor (OpenRA.ObjectCreator creator, System.String name, OpenRA.MiniYaml node) [0x00066] in <a10404fca1ef4990a0ba356e4aea33c3>:0 
  at OpenRA.Ruleset+<LoadDefaults>c__AnonStorey0.<>m__1 (OpenRA.MiniYamlNode k) [0x00016] in <a10404fca1ef4990a0ba356e4aea33c3>:0 
  at OpenRA.Exts.ToDictionaryWithConflictLog[TSource,TKey,TElement] (System.Collections.Generic.IEnumerable`1[T] source, System.Func`2[T,TResult] keySelector, System.Func`2[T,TResult] elementSelector, System.String debugName, System.Func`2[T,TResult] logKey, System.Func`2[T,TResult] logValue) [0x00071] in <a10404fca1ef4990a0ba356e4aea33c3>:0 
  at OpenRA.Ruleset.MergeOrDefault[T] (System.String name, OpenRA.FileSystem.IReadOnlyFileSystem fileSystem, System.Collections.Generic.IEnumerable`1[T] files, OpenRA.MiniYaml additional, OpenRA.IReadOnlyDictionary`2[TKey,TValue] defaults, System.Func`2[T,TResult] makeObject) [0x0003c] in <a10404fca1ef4990a0ba356e4aea33c3>:0 
  at OpenRA.Ruleset+<LoadDefaults>c__AnonStorey0.<>m__0 () [0x00001] in <a10404fca1ef4990a0ba356e4aea33c3>:0 
  at System.Threading.Tasks.Task.InnerInvoke () [0x00012] in <8f2c484307284b51944a1a13a14c0266>:0 
  at System.Threading.Tasks.Task.Execute () [0x00016] in <8f2c484307284b51944a1a13a14c0266>:0 
  at System.Threading.Tasks.Task.ThrowIfExceptional (System.Boolean includeTaskCanceledExceptions) [0x00014] in <8f2c484307284b51944a1a13a14c0266>:0 
  at System.Threading.Tasks.Task.Wait (System.Int32 millisecondsTimeout, System.Threading.CancellationToken cancellationToken) [0x00052] in <8f2c484307284b51944a1a13a14c0266>:0 
  at System.Threading.Tasks.Task.Wait (System.Int32 millisecondsTimeout) [0x00000] in <8f2c484307284b51944a1a13a14c0266>:0 
  at OpenRA.Ruleset.LoadDefaults (OpenRA.ModData modData) [0x0007d] in <a10404fca1ef4990a0ba356e4aea33c3>:0 
  at OpenRA.ModData.<ModData>m__2 () [0x00000] in <a10404fca1ef4990a0ba356e4aea33c3>:0 
  at System.Lazy`1[T].CreateValue () [0x00075] in <8f2c484307284b51944a1a13a14c0266>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <8f2c484307284b51944a1a13a14c0266>:0 
  at System.Lazy`1[T].get_Value () [0x00032] in <8f2c484307284b51944a1a13a14c0266>:0 
  at OpenRA.ModData.get_DefaultRules () [0x00001] in <a10404fca1ef4990a0ba356e4aea33c3>:0 
  at OpenRA.Ruleset.LoadDefaultsForTileSet (OpenRA.ModData modData, System.String tileSet) [0x00001] in <a10404fca1ef4990a0ba356e4aea33c3>:0 
  at OpenRA.Map.PostInit () [0x0004d] in <a10404fca1ef4990a0ba356e4aea33c3>:0 
  at OpenRA.Map..ctor (OpenRA.ModData modData, OpenRA.FileSystem.IReadOnlyPackage package) [0x00414] in <a10404fca1ef4990a0ba356e4aea33c3>:0 
  at OpenRA.ModData.PrepareMap (System.String uid) [0x00069] in <a10404fca1ef4990a0ba356e4aea33c3>:0 
  at OpenRA.Game.StartGame (System.String mapUID, OpenRA.WorldType type) [0x0003a] in <a10404fca1ef4990a0ba356e4aea33c3>:0 
  at OpenRA.Game.LoadShellMap () [0x00017] in <a10404fca1ef4990a0ba356e4aea33c3>:0 
  at OpenRA.Mods.Common.LoadScreens.BlankLoadScreen.StartGame (OpenRA.Arguments args) [0x001b4] in <9834f99f66274714ae00f7a4cff170fc>:0 
  at OpenRA.Game.InitializeMod (System.String mod, OpenRA.Arguments args) [0x0038d] in <a10404fca1ef4990a0ba356e4aea33c3>:0 
  at OpenRA.Game.Initialize (OpenRA.Arguments args) [0x0032d] in <a10404fca1ef4990a0ba356e4aea33c3>:0 
  at OpenRA.Program.Run (System.String[] args) [0x00007] in <a10404fca1ef4990a0ba356e4aea33c3>:0 
  at OpenRA.Program.Main (System.String[] args) [0x0004f] in <a10404fca1ef4990a0ba356e4aea33c3>:0 
`

Running Debian Stretch, amd64, Mono JIT compiler version 4.6.2 (Debian 4.6.2.7+dfsg-1), mesa 13.0.2-3

**Comment by IntelMiner** [comment] 2017-01-16 05:29
Getting the same issue under Gentoo x64

**Comment by AmEv7Fam** [comment] 2017-01-17 17:01
Very similar issue, Win10.
```
Red Alert 2 Mod at Version git-ef5d7b3
Date: 2017-01-17 16:56:57Z
Operating System: Windows (Microsoft Windows NT 6.2.9200.0)
Runtime Version: .NET CLR 4.0.30319.42000
Exception of type `System.AggregateException`: One or more errors occurred.
Inner
  Exception of type `System.InvalidOperationException`: Cannot locate type: UpgradeManagerInfo
     at OpenRA.ObjectCreator.<.cctor>b__1d(String s)
   at OpenRA.ObjectCreator.CreateObject[T](String className, Dictionary`2 args)
   at OpenRA.ObjectCreator.CreateObject[T](String className)
   at OpenRA.ActorInfo.LoadTraitInfo(ObjectCreator creator, String traitName, MiniYaml my)
   at OpenRA.ActorInfo..ctor(ObjectCreator creator, String name, MiniYaml node)
   at OpenRA.Ruleset.<>c__DisplayClass9.<LoadDefaults>b__4(MiniYamlNode k)
   at OpenRA.Exts.ToDictionaryWithConflictLog[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, String debugName, Func`2 logKey, Func`2 logValue)
   at OpenRA.Ruleset.MergeOrDefault[T](String name, IReadOnlyFileSystem fileSystem, IEnumerable`1 files, MiniYaml additional, IReadOnlyDictionary`2 defaults, Func`2 makeObject)
   at OpenRA.Ruleset.<>c__DisplayClass9.<LoadDefaults>b__3()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout)
   at OpenRA.Ruleset.LoadDefaults(ModData modData)
   at OpenRA.ModData.<.ctor>b__2()
   at System.Lazy`1.CreateValue()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Lazy`1.get_Value()
   at OpenRA.ModData.get_DefaultRules()
   at OpenRA.Ruleset.LoadDefaultsForTileSet(ModData modData, String tileSet)
   at OpenRA.Map.PostInit()
   at OpenRA.Map..ctor(ModData modData, IReadOnlyPackage package)
   at OpenRA.ModData.PrepareMap(String uid)
   at OpenRA.Game.StartGame(String mapUID, WorldType type)
   at OpenRA.Game.LoadShellMap()
   at OpenRA.Mods.Common.LoadScreens.BlankLoadScreen.StartGame(Arguments args)
   at OpenRA.Game.InitializeMod(String mod, Arguments args)
   at OpenRA.Game.Initialize(Arguments args)
   at OpenRA.Program.Run(String[] args)
   at OpenRA.Program.Main(String[] args)
```

**Comment by GraionDilach** [comment] 2017-01-17 18:22
Duplicate of #346.

**Comment by GraionDilach** [comment] 2017-01-17 18:22
Also see #354.

**Closed by GraionDilach** 2017-01-17 18:22 UTC
Labels: Crash
