### ISSUE TITLE
Veterancy system needs to get ported to the new Conditions system

### ISSUE THREAD

**Issue by Fincer** [OpenRA/ra2#341] opened 2016-12-10 23:39 UTC
I checked other open issues here, it seems that this is somehow different, though the result is same (can't load RA2 mod). After successful build (openra bleed/git + ra2 mod), the mod doesn't work. Exception log file says as follows:

```
Red Alert 2 Mod at Version git-fa23517
Date: 2016-12-10 23:38:16Z
Operating System: Linux (Unix 3.17.4.1)
Runtime Version: Mono 4.6.1 (Stable 4.6.1.3/abb06f1 Mon Oct  3 07:51:42 UTC 2016) CLR 4.0.30319.42000
Exception of type `System.AggregateException`: One or more errors occurred.
Inner
  Exception of type `OpenRA.YamlException`: Actor type ^amcv.colorpicker: FieldLoader: Cannot parse `110, 130` into `Modifier.System.Int32` 
    at OpenRA.ActorInfo..ctor (OpenRA.ObjectCreator creator, System.String name, OpenRA.MiniYaml node) [0x000e4] in <51fa7bb79852460fbc91d4f9abed36a4>:0 
  at OpenRA.Ruleset+<LoadDefaults>c__AnonStorey0.<>m__1 (OpenRA.MiniYamlNode k) [0x00016] in <51fa7bb79852460fbc91d4f9abed36a4>:0 
  at OpenRA.Exts.ToDictionaryWithConflictLog[TSource,TKey,TElement] (System.Collections.Generic.IEnumerable`1[T] source, System.Func`2[T,TResult] keySelector, System.Func`2[T,TResult] elementSelector, System.String debugName, System.Func`2[T,TResult] logKey, System.Func`2[T,TResult] logValue) [0x00071] in <51fa7bb79852460fbc91d4f9abed36a4>:0 
  at OpenRA.Ruleset.MergeOrDefault[T] (System.String name, OpenRA.FileSystem.IReadOnlyFileSystem fileSystem, System.Collections.Generic.IEnumerable`1[T] files, OpenRA.MiniYaml additional, OpenRA.IReadOnlyDictionary`2[TKey,TValue] defaults, System.Func`2[T,TResult] makeObject) [0x0003c] in <51fa7bb79852460fbc91d4f9abed36a4>:0 
  at OpenRA.Ruleset+<LoadDefaults>c__AnonStorey0.<>m__0 () [0x00001] in <51fa7bb79852460fbc91d4f9abed36a4>:0 
  at System.Threading.Tasks.Task.InnerInvoke () [0x00012] in /build/mono/src/mono-4.6.1/mcs/class/referencesource/mscorlib/system/threading/Tasks/Task.cs:2879 
  at System.Threading.Tasks.Task.Execute () [0x00016] in /build/mono/src/mono-4.6.1/mcs/class/referencesource/mscorlib/system/threading/Tasks/Task.cs:2502 
  at System.Threading.Tasks.Task.ThrowIfExceptional (System.Boolean includeTaskCanceledExceptions) [0x00014] in /build/mono/src/mono-4.6.1/mcs/class/referencesource/mscorlib/system/threading/Tasks/Task.cs:2157 
  at System.Threading.Tasks.Task.Wait (System.Int32 millisecondsTimeout, System.Threading.CancellationToken cancellationToken) [0x00052] in /build/mono/src/mono-4.6.1/mcs/class/referencesource/mscorlib/system/threading/Tasks/Task.cs:3189 
  at System.Threading.Tasks.Task.Wait (System.Int32 millisecondsTimeout) [0x00000] in /build/mono/src/mono-4.6.1/mcs/class/referencesource/mscorlib/system/threading/Tasks/Task.cs:3130 
  at OpenRA.Ruleset.LoadDefaults (OpenRA.ModData modData) [0x0007d] in <51fa7bb79852460fbc91d4f9abed36a4>:0 
  at OpenRA.ModData.<ModData>m__2 () [0x00000] in <51fa7bb79852460fbc91d4f9abed36a4>:0 
  at System.Lazy`1[T].CreateValue () [0x00075] in <dca3b561b8ad4f9fb10141d81b39ff45>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in /build/mono/src/mono-4.6.1/mcs/class/referencesource/mscorlib/system/runtime/exceptionservices/exceptionservicescommon.cs:143 
  at System.Lazy`1[T].get_Value () [0x00032] in <dca3b561b8ad4f9fb10141d81b39ff45>:0 
  at OpenRA.ModData.get_DefaultRules () [0x00001] in <51fa7bb79852460fbc91d4f9abed36a4>:0 
  at OpenRA.Ruleset.LoadDefaultsForTileSet (OpenRA.ModData modData, System.String tileSet) [0x00001] in <51fa7bb79852460fbc91d4f9abed36a4>:0 
  at OpenRA.Map.PostInit () [0x0004d] in <51fa7bb79852460fbc91d4f9abed36a4>:0 
  at OpenRA.Map..ctor (OpenRA.ModData modData, OpenRA.FileSystem.IReadOnlyPackage package) [0x00414] in <51fa7bb79852460fbc91d4f9abed36a4>:0 
  at OpenRA.ModData.PrepareMap (System.String uid) [0x00069] in <51fa7bb79852460fbc91d4f9abed36a4>:0 
  at OpenRA.Game.StartGame (System.String mapUID, OpenRA.WorldType type) [0x0003a] in <51fa7bb79852460fbc91d4f9abed36a4>:0 
  at OpenRA.Game.LoadShellMap () [0x00017] in <51fa7bb79852460fbc91d4f9abed36a4>:0 
  at OpenRA.Mods.Common.LoadScreens.BlankLoadScreen.StartGame (OpenRA.Arguments args) [0x001b4] in <e07816779dec4856b09e24d33ec71eda>:0 
  at OpenRA.Game.InitializeMod (System.String mod, OpenRA.Arguments args) [0x0038d] in <51fa7bb79852460fbc91d4f9abed36a4>:0 
  at OpenRA.Game.Initialize (OpenRA.Arguments args) [0x0032d] in <51fa7bb79852460fbc91d4f9abed36a4>:0 
  at OpenRA.Program.Run (System.String[] args) [0x00007] in <51fa7bb79852460fbc91d4f9abed36a4>:0 
  at OpenRA.Program.Main (System.String[] args) [0x0004f] in <51fa7bb79852460fbc91d4f9abed36a4>:0 
```

**Comment by LinuxDonald** [comment] 2016-12-11 01:15
Maybe because alot rewrites that got merged into openra master.

**Comment by Fincer** [comment] 2016-12-11 10:34
Yeah, that's what I suspect, too.

**Comment by v1nce** [comment] 2016-12-19 17:14
same here

**Comment by v1nce** [comment] 2016-12-19 23:39
If you edit /rules/defaults.yaml in ra2 you'll see  	
FirepowerMultiplier@experience:
		Modifier: 110, 130

while in ra/rules/defaults.yaml there is one entry per level
	FirepowerMultiplier@RANK-1:
		RequiresCondition: rank-veteran-1 && !rank-veteran-2
		Modifier: 105
	FirepowerMultiplier@RANK-2:
		RequiresCondition: rank-veteran-2 && !rank-veteran-3
		Modifier: 110
	FirepowerMultiplier@RANK-3:
		RequiresCondition: rank-veteran-3 && !rank-elite

the yaml parser failed in ra2 because it expected one int and not a array of int.

right now I didn't find where this should get fixed

**Comment by v1nce** [comment] 2016-12-19 23:42
if you edit all Modifier in defaults.yaml then you get another error

Platform is Linux
Using SDL 2 with OpenGL renderer
Desktop resolution: 1920x1080
No custom resolution provided, using desktop resolution
Using resolution: 1920x1080
OpenGL version: 3.3.0 NVIDIA 340.98
Using default sound device
Available mods:
	all: All mods ({DEV_VERSION})
	cnc: Tiberian Dawn ({DEV_VERSION})
	d2k: Dune 2000 ({DEV_VERSION})
	modchooser: Mod Chooser ({DEV_VERSION})
	ra: Red Alert ({DEV_VERSION})
	ra2: Red Alert 2 ({DEV_VERSION})
	ts: Tiberian Sun ({DEV_VERSION})
Loading mod: ra2
Exception of type `System.AggregateException`: One or more errors occurred.
Inner
  Exception of type `System.InvalidOperationException`: Cannot locate type: WithRankDecorationInfo
    at OpenRA.ObjectCreator.<MissingTypeAction>m__6 (System.String s) [0x00015] in <8716fee1ffbd40bfb70336b273aa036b>:0 
  at OpenRA.ObjectCreator.CreateObject[T] (System.String className, System.Collections.Generic.Dictionary`2[TKey,TValue] args) [0x0001b] in <8716fee1ffbd40bfb70336b273aa036b>:0 
  at OpenRA.ObjectCreator.CreateObject[T] (System.String className) [0x00008] in <8716fee1ffbd40bfb70336b273aa036b>:0 
  at OpenRA.ActorInfo.LoadTraitInfo (OpenRA.ObjectCreator creator, System.String traitName, OpenRA.MiniYaml my) [0x00040] in <8716fee1ffbd40bfb70336b273aa036b>:0 
  at OpenRA.ActorInfo..ctor (OpenRA.ObjectCreator creator, System.String name, OpenRA.MiniYaml node) [0x00066] in <8716fee1ffbd40bfb70336b273aa036b>:0 
  at OpenRA.Ruleset+<LoadDefaults>c__AnonStorey0.<>m__1 (OpenRA.MiniYamlNode k) [0x00016] in <8716fee1ffbd40bfb70336b273aa036b>:0 
  at OpenRA.Exts.ToDictionaryWithConflictLog[TSource,TKey,TElement] (System.Collections.Generic.IEnumerable`1[T] source, System.Func`2[T,TResult] keySelector, System.Func`2[T,TResult] elementSelector, System.String debugName, System.Func`2[T,TResult] logKey, System.Func`2[T,TResult] logValue) [0x00071] in <8716fee1ffbd40bfb70336b273aa036b>:0 
  at OpenRA.Ruleset.MergeOrDefault[T] (System.String name, OpenRA.FileSystem.IReadOnlyFileSystem fileSystem, System.Collections.Generic.IEnumerable`1[T] files, OpenRA.MiniYaml additional, OpenRA.IReadOnlyDictionary`2[TKey,TValue] defaults, System.Func`2[T,TResult] makeObject) [0x0003c] in <8716fee1ffbd40bfb70336b273aa036b>:0 
  at OpenRA.Ruleset+<LoadDefaults>c__AnonStorey0.<>m__0 () [0x00001] in <8716fee1ffbd40bfb70336b273aa036b>:0 
  at System.Threading.Tasks.Task.InnerInvoke () [0x00012] in <8f2c484307284b51944a1a13a14c0266>:0 
  at System.Threading.Tasks.Task.Execute () [0x00016] in <8f2c484307284b51944a1a13a14c0266>:0 
  at System.Threading.Tasks.Task.ThrowIfExceptional (System.Boolean includeTaskCanceledExceptions) [0x00014] in <8f2c484307284b51944a1a13a14c0266>:0 
  at System.Threading.Tasks.Task.Wait (System.Int32 millisecondsTimeout, System.Threading.CancellationToken cancellationToken) [0x00052] in <8f2c484307284b51944a1a13a14c0266>:0 
  at System.Threading.Tasks.Task.Wait (System.Int32 millisecondsTimeout) [0x00000] in <8f2c484307284b51944a1a13a14c0266>:0 
  at OpenRA.Ruleset.LoadDefaults (OpenRA.ModData modData) [0x0007d] in <8716fee1ffbd40bfb70336b273aa036b>:0 
  at OpenRA.ModData.<ModData>m__2 () [0x00000] in <8716fee1ffbd40bfb70336b273aa036b>:0 
  at System.Lazy`1[T].CreateValue () [0x00075] in <8f2c484307284b51944a1a13a14c0266>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <8f2c484307284b51944a1a13a14c0266>:0 
  at System.Lazy`1[T].get_Value () [0x00032] in <8f2c484307284b51944a1a13a14c0266>:0 
  at OpenRA.ModData.get_DefaultRules () [0x00001] in <8716fee1ffbd40bfb70336b273aa036b>:0 
  at OpenRA.Ruleset.LoadDefaultsForTileSet (OpenRA.ModData modData, System.String tileSet) [0x00001] in <8716fee1ffbd40bfb70336b273aa036b>:0 
  at OpenRA.Map.PostInit () [0x0004d] in <8716fee1ffbd40bfb70336b273aa036b>:0 
  at OpenRA.Map..ctor (OpenRA.ModData modData, OpenRA.FileSystem.IReadOnlyPackage package) [0x00414] in <8716fee1ffbd40bfb70336b273aa036b>:0 
  at OpenRA.ModData.PrepareMap (System.String uid) [0x00069] in <8716fee1ffbd40bfb70336b273aa036b>:0 
  at OpenRA.Game.StartGame (System.String mapUID, OpenRA.WorldType type) [0x0003a] in <8716fee1ffbd40bfb70336b273aa036b>:0 
  at OpenRA.Game.LoadShellMap () [0x00017] in <8716fee1ffbd40bfb70336b273aa036b>:0 
  at OpenRA.Mods.Common.LoadScreens.BlankLoadScreen.StartGame (OpenRA.Arguments args) [0x001b4] in <4147d659708847269d6771dc994d9067>:0 
  at OpenRA.Game.InitializeMod (System.String mod, OpenRA.Arguments args) [0x0038e] in <8716fee1ffbd40bfb70336b273aa036b>:0 
  at OpenRA.Game.Initialize (OpenRA.Arguments args) [0x0032d] in <8716fee1ffbd40bfb70336b273aa036b>:0 
  at OpenRA.Program.Run (System.String[] args) [0x00007] in <8716fee1ffbd40bfb70336b273aa036b>:0 
  at OpenRA.Program.Main (System.String[] args) [0x0004f] in <8716fee1ffbd40bfb70336b273aa036b>:0 

AL lib: FreeContext: (0x1697a20) Deleting 32 Source(s)

**Comment by Fincer** [comment] 2016-12-21 16:07
Fixing the issue seems to be quite low priority task since it's blocking the gameplay of the RA2 mod (i.e. critical issue) but no-one taking care of fixing it (anyway, good findings v1nce, thanks for that). I'm not too familiar with the codebase to fix the issue once and for all. Someone who is capable of doing it, should do it.

I don't think anything's going to happen before XMas or New Year. After the next RA playtest release has been published there might be some hope this issue gets more attention. But for now, don't get your hopes up too much. In addition, Tiberian Sun mod (and OpenRA engine) is still in development (features being added etc.) so the progress may constantly break "unofficial" RA2 mod, as it likely did now. I mean, in the future, too.

Sorry for the off-topic, just speaking my mind out loud. Happy holidays, anyway!

**Comment by GraionDilach** [comment] 2016-12-21 17:40
Well, I gradually lost interest in this project when random nonsense were added just because "throwing new dependencies into this are good" - aka #267.

The RA2 mod is quite simple in terms of stuff, so a semi-skilled bleed modder would be capable of maintaining it (the skill level is high alone due to the traits it has which might break at cases, like the activities rewrite).

**Comment by Mailaender** [comment] 2017-01-01 11:04
See https://github.com/OpenRA/OpenRA/pull/12381 for the changes required to resolve this.

**Comment by cookgreen** [comment] 2017-01-01 13:24
I think there is a lot work to do with the yaml file error, i try to fix some, but it still many. I try to upgrade the mod yaml file with OpenRA.Utility.exe, but it crashed :(

**Comment by Mailaender** [comment] 2017-01-02 19:16
I see https://github.com/OpenRA/ra2/issues/352 that shouldn't happen, but that utility doesn't get tested a lot.

**Comment by GraionDilach** [comment] 2017-01-17 18:23
Reverse-duplicate of #354.

**Closed by GraionDilach** 2017-01-17 18:23 UTC
Labels: Crash
