### ISSUE TITLE
Freeze on 'ESC' key pressed

### ISSUE THREAD

**Issue by jaylevin** [OpenRA/ra2#405] opened 2017-12-06 02:56 UTC
I create a server in the multiplayer menu, join it from a computer in the same network as me. Game runs fine, beautiful job to this development team. However, when either computer presses ESC during the game, the program will crash and throw this exception:

https://hastebin.com/epadumugaw.pas

**Comment by Mailaender** [comment] 2017-12-12 11:26
Duplicate of https://github.com/OpenRA/OpenRA/issues/14474.

**Closed by Mailaender** 2017-12-12 11:26 UTC
Labels: Crash
