### ISSUE TITLE
RA2 Crashed —— Actor type ^amcv.colorpicker: FieldLoader: Cannot parse `110, 130` into `Modifier.System.Int32` 

### ISSUE THREAD

**Issue by cookgreen** [OpenRA/ra2#348] opened 2017-01-01 02:14 UTC
`Exception of type `OpenRA.YamlException`: Actor type ^amcv.colorpicker: FieldLoader: Cannot parse `110, 130` into `Modifier.System.Int32` `

**Comment by Mailaender** [comment] 2017-01-01 11:03
Duplicate of https://github.com/OpenRA/ra2/issues/341.

**Closed by Mailaender** 2017-01-01 11:03 UTC
