### ISSUE TITLE
GL Error: 1285

### ISSUE THREAD

**Issue by SteamsDev** [OpenRA/ra2#273] opened 2016-07-08 19:09 UTC
So, I've tried to load the RA2 Mod for OpenRA, and after my game kept crashing, I was a little confused about the debug and exception logs. I thought I had done everything correctly, but I don't know what to do next.
These are the recent debug and exception files for the game. Is there anything I can do to fix the problem?

[debug.txt](https://github.com/OpenRA/ra2/files/354930/debug.txt)
[exception.txt](https://github.com/OpenRA/ra2/files/354931/exception.txt)

**Comment by abcdefg30** [comment] 2016-07-08 22:17
This looks like you don't have the `OpenRA.Mods.RA2.dll`. Did you compile it? If yes and the error is still showing up, try copying `OpenRA.Mods.RA2.dll` from `OpenRA.Mods.RA2\bin\Debug\` into the main folder.

**Comment by SteamsDev** [comment] 2016-07-09 00:16
There's one problem with that: I looked in my `OpenRA.Mods.RA2\bin\Debug\` folder, but the `OpenRA.Mods.Ra2.dll` file isn't there, and I can't seem to find it on my computer. Am I missing something? Can I get the file from somewhere?

**Comment by SteamsDev** [comment] 2016-07-09 10:11
Nevermind. I found it at one point. I think I may have another issue, though. I'll keep you notified.

**Comment by SteamsDev** [comment] 2016-07-09 19:43
Well, now I think I have a performance issue, but I just want to make sure.
[exception1.txt](https://github.com/OpenRA/ra2/files/355726/exception1.txt)
[debug1.txt](https://github.com/OpenRA/ra2/files/355727/debug1.txt)

**Comment by abcdefg30** [comment] 2016-07-10 13:42
We need your `graphics.log` to tell more.

**Comment by SteamsDev** [comment] 2016-07-27 11:03
Okay. Here it is.
[graphics.txt](https://github.com/OpenRA/ra2/files/385879/graphics.txt)

**Comment by GraionDilach** [comment] 2016-07-27 12:08
What is your exact GPU - I assume something around Intel HD 2000/3000, but that's just my guess from the OpenGL list.

**Comment by Mailaender** [comment] 2016-07-27 12:48
This seems to be an out of memory crash. At this point the engine isn't properly optimized so you need better hardware or help rewrite the internals to be less wasteful for large sprite sheets.

**Comment by SteamsDev** [comment] 2016-07-28 01:14
This is some of the information about my graphics.
Name: Intel HD Graphics
Chip Type: Core i5
Approx. Total Memory: 1696MB
Display Mode: 1366x768 (32-Bit)(60Hz)

Looking at this, I do believe it is Intel HD 2000, but I'm not sure.

**Comment by GraionDilach** [comment] 2016-07-28 06:10
In case of HD 2000 (means you have an Intel i5-2X00), the main problem is that this particular series of GPU has only 64 MB VRAM, which cannot be increased. The issue in that case is that due to how tilesets are used by the engine, this 64 MB VRAM will be almost entirely allocated for the terrain alone, which leaves no texture space to put units/etc into.

**Comment by SteamsDev** [comment] 2016-07-30 20:25
I have a question: Is it possible to use the RA2 units and buildings and stuff while still having regular RA terrain, do I need the RA2 terrain to run the full game, or does it not matter at all?

**Comment by abcdefg30** [comment] 2016-07-30 22:18
Unfortunately it's very unlikely that you can get RA2 to run with RA terrain (you would need to change the tileset yamls a lot, and you'd loose MP capability).

**Comment by Mailaender** [comment] 2016-07-31 06:21
Closing as a duplicate of https://github.com/OpenRA/OpenRA/issues/11359.

**Closed by Mailaender** 2016-07-31 06:21 UTC
Labels: Crash

**Comment by Mailaender** [comment] 2016-07-31 06:24
> OpenGL Information:
> Vendor: Intel
> Renderer: Intel(R) HD Graphics
> GL Version: 2.1.0 - Build 8.15.10.2418
> Shader Version: 1.20  - Intel Build 8.15.10.2418

Also try downloading the latest drivers from https://downloadcenter.intel.com/product/81502/Intel-HD-Graphics-2000-for-2nd-Generation-Intel-Core-Processors

**Comment by chrisforbes** [comment] 2016-07-31 11:10
@Mailaender That's not a baby version of Sandybridge (2000/3000), that's Ironlake.

**Comment by Mailaender** [comment] 2016-07-31 11:30
Yeah, sorry I just picked the first link to see if 8.15 is something recent. Go to https://downloadcenter.intel.com/ and use their auto-detection tools or whatever.

**Comment by SteamsDev** [comment] 2016-08-01 19:08
Well, I have some news for you: the mod is able to run a single game on my computer, but I think the reason is that my computer decided to cut the terrain in order to leave room for all the other stuff. This includes flat areas, cliffs, and water, but ore or gems.
I'm not able to get a screenshot right now, but I'll post one for you as soon as I can.

**Comment by Mailaender** [comment] 2016-08-01 19:16
Press `CTRL + P` and look in My Documents\OpenRA\Screenshots for images to upload here.

**Comment by SteamsDev** [comment] 2016-08-01 21:25
This is the best screenshot I could get. My game crashed trying to go further.
![openra-2016-08-01t212330z](https://cloud.githubusercontent.com/assets/20361090/17309463/f39f5fa2-580c-11e6-9b82-d7060d8ba28a.png)

**Comment by SteamsDev** [comment] 2016-08-02 14:29
Update for Graion Dilach: I have further information on my graphics processor:
![intel graphics info](https://cloud.githubusercontent.com/assets/20361090/17332158/ca2dc066-589b-11e6-9b95-a22d49507ed6.png)
Does this tell you anything?

**Comment by GraionDilach** [comment] 2016-08-04 14:42
Oh damn, you're a gen older than me in terms of Intel graphics.

Intel came up with the solution of detecting and allocating additional VRAM during execution runtime, per the application's request years and gens ago, however it seems OpenRA's VRAM requesting method - either due to OpenRA's, the OpenGL-to-C# wrapper's, or OpenGL's own fault - does not trigger the VRAM allocation, which is why stuff blows up at you.

Sadly, I don't know of any fix to this. :(

**Comment by Mailaender** [comment] 2016-08-06 09:06
It seems to be bad old Intel Windows drivers and we don't workaround their problems. What you can do is install any recent Linux distribution at no cost to get an immediate fix or upgrade your hardware. Intel HD 4000 works fine for me.

**Comment by SteamsDev** [comment] 2016-09-13 20:06
Sorry I haven't given a quick reply, but now I have a problem: upon building Ubuntu 16.04, it gave me this error message: `Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.` It also can't seem to find `OpenRA.Game.exe` even though I have it inside `~/build/OpenRA`. Can you help?

**Comment by SteamsDev** [comment] 2016-09-19 19:56
Updated Screenshot on Win7/Intel i5:
![openra-2016-09-19t235239z](https://cloud.githubusercontent.com/assets/20361090/18646862/7cb3f376-7e81-11e6-9522-2bf75e008b44.png)
So now I know the mod at least works on my computer.
