### ISSUE TITLE
Game crashes if GI is deployed while attacking.

### ISSUE THREAD

**Issue by GraionDilach** [OpenRA/ra2#558] opened 2019-04-20 18:16 UTC
AttackFrontal's RequiresCondition needs to be undeployed instead of !deployed.

**Comment by sorcerer86pt** [comment] 2019-04-20 21:41
Hi. 
I couldn't reproduce the problem.
Can you detail more on how to trigger the crash?

**Comment by GraionDilach** [comment] 2019-04-20 21:44
Could be something which only happens at a later engine revision - I discovered this while bumping versions beyond last release for my own use.

**Comment by sorcerer86pt** [comment] 2019-04-20 21:47
i see. so it could be more of a momentary incompatibility between GI deployment and new engine. I will bump the engine and check.

**Comment by GraionDilach** [comment] 2019-04-20 22:05
Relevant crashlog.

```
OpenRA engine version {DEV_VERSION}
Red Alert 2 mod version {DEV_VERSION}
on map d54deadfb8ecfea8f5fc59fbd659fb4f211b13d3 (DEFCON 6 by Westwood Studios).
Date: 2019-04-20 17:47:50Z
Operating System: Windows (Microsoft Windows NT 6.2.9200.0)
Runtime Version: .NET CLR 4.0.30319.42000
Exception of type `System.InvalidOperationException`: Sequence contains no elements
   at System.Linq.Enumerable.Min[TSource](IEnumerable`1 source)
   at System.Linq.Enumerable.Min[TSource,TResult](IEnumerable`1 source, Func`2 selector)
   at OpenRA.Mods.Common.Activities.Attack.Tick(Actor self) in d:\OpenRA-AS-dev\OpenRA.Mods.Common\Activities\Attack.cs:line 88
   at OpenRA.Activities.Activity.TickOuter(Actor self) in d:\OpenRA-AS-dev\OpenRA.Game\Activities\Activity.cs:line 158
   at OpenRA.Traits.ActivityUtils.RunActivity(Actor self, Activity act) in d:\OpenRA-AS-dev\OpenRA.Game\Traits\ActivityUtils.cs:line 37
   at OpenRA.Actor.Tick() in d:\OpenRA-AS-dev\OpenRA.Game\Actor.cs:line 144
   at OpenRA.World.Tick() in d:\OpenRA-AS-dev\OpenRA.Game\World.cs:line 364
   at OpenRA.Game.InnerLogicTick(OrderManager orderManager) in d:\OpenRA-AS-dev\OpenRA.Game\Game.cs:line 602
   at OpenRA.Game.LogicTick() in d:\OpenRA-AS-dev\OpenRA.Game\Game.cs:line 626
   at OpenRA.Game.Loop() in d:\OpenRA-AS-dev\OpenRA.Game\Game.cs:line 756
   at OpenRA.Game.Run() in d:\OpenRA-AS-dev\OpenRA.Game\Game.cs:line 796
   at OpenRA.Game.InitializeAndRun(String[] args) in d:\OpenRA-AS-dev\OpenRA.Game\Game.cs:line 254
   at OpenRA.Program.Main(String[] args) in d:\OpenRA-AS-dev\OpenRA.Game\Support\Program.cs:line 37
```

**Comment by sorcerer86pt** [comment] 2020-02-10 21:43
just a ping... Is that still happening with new engine, or we can close this with couldn't reproduce?

**Comment by sorcerer86pt** [comment] 2020-03-08 00:55
I Can confirm that the bug is happening:
Steps to reproduce:

- have a GI attack any unit while not deployed
- press the Deploy hotkey


`\launch-game.cmd : Exception of type `System.InvalidOperationException`: Sequence contains no elements
At line:1 char:1
+ .\launch-game.cmd
+ ~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (Exception of ty...ont‚m elementos:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
   em System.Linq.Enumerable.Min[TSource](IEnumerable`1 source)
   em OpenRA.Mods.Common.Activities.Attack.Tick(Actor self)
   em OpenRA.Activities.Activity.TickOuter
(Actor self)
   em OpenRA.Traits.ActivityUtils.RunActivity(Actor self, Activity act)
   em OpenRA.Actor.Tick()
   em OpenRA.World.Tick()
   em OpenRA.Game.InnerLogicTick(OrderManager orderManager)
   em OpenRA.Game.LogicTick()
   em OpenRA.Game.Loop()
   em OpenRA.Game.Run()
   em OpenRA.Game.InitializeAndRun(String[] args)
   em OpenRA.Program.Main(String[] args)`

Exception Log content:
`OpenRA engine version playtest-20200118
Red Alert 2 mod version {DEV_VERSION}
on map 3a94af24afc3d43b59eecdff309bbe44c5047644 (Pitch Point by Westwood Studios).
Date: 2020-03-08 00:51:18Z
Operating System: Windows (Microsoft Windows NT 6.2.9200.0)
Runtime Version: .NET CLR 4.0.30319.42000
Exception of type `System.InvalidOperationException`: A sequência não contém elementos
   em System.Linq.Enumerable.Min[TSource](IEnumerable`1 source)
   em OpenRA.Mods.Common.Activities.Attack.Tick(Actor self)
   em OpenRA.Activities.Activity.TickOuter(Actor self)
   em OpenRA.Traits.ActivityUtils.RunActivity(Actor self, Activity act)
   em OpenRA.Actor.Tick()
   em OpenRA.World.Tick()
   em OpenRA.Game.InnerLogicTick(OrderManager orderManager)
   em OpenRA.Game.LogicTick()
   em OpenRA.Game.Loop()
   em OpenRA.Game.Run()
   em OpenRA.Game.InitializeAndRun(String[] args)
   em OpenRA.Program.Main(String[] args)
`

**Closed** 2020-03-08 21:01 UTC
Labels: Crash
