### ISSUE TITLE
Issues i noticed

### ISSUE THREAD

**Issue by MustaphaTR** [OpenRA/ra2#198] opened 2016-05-02 06:19 UTC
- [ ] Repair anim is drawn below buildings, at least i saw it on Allied PP.

- [ ] Allied and Soviet CYard costs are inaccurate. Allied one is 3000, Soviet one is 2500.

- [ ] Cargo Plane's health is invisible. I think this is a problem that should be solved on upstream, but for vanilla RA2's unselectable units you can see its health by hovering cursor on it.

**Comment by Mailaender** [comment] 2016-05-16 07:40
I assume the first one is a duplicate of https://github.com/OpenRA/ra2/issues/119. Please open tickets with one problem per issue and a useful headline or send a pull request right away.

**Closed by Mailaender** 2016-05-16 07:40 UTC
Labels: Bug
